# Enable Kodiak
version = 1

[merge]
# Required label
# Forces label requirements
require_automerge_label = true

# Labels for Automerge
# This Label is shared with Luna.
#-----------------------------------
# Conflicts are avoided by explicitly blacklisting Actor:Luna label
# Luna handles this gracefullym by first adding this label before doing
# any other tasks. If adding Actor:Luna label fails, Luna will not act
# on that PR/Issue.
automerge_label = "luna/automerge"

# Methods
method = "squash"

# Blacklisted Labels
# luna                                            - Prevent conflicts with Luna
# s/wip, s/blocked, s/pending, s/review-required  - Prevent merging WIP or blocked PRs
# s/stale, s/locked                               - Prevent merging stale PRs
blocking_labels = ["luna", "s/blocked", "s/pending", "s/wip", "s/review-required", "s/stale", "s/pending", "s/wont-fix"]

# Priority
priority_merge_label = "p/critical"

# Cleanup stale branches
delete_branch_on_merge = true

# On conflicts, remove automerge labels
notify_on_conflict = true

# Wait to Pass checks
optimistic_updates = false

[merge.message]
body = "pull_request_body"
strip_html_comments = true
body_type = "markdown"
cut_body_before = "<!-- COMMIT-NOTES-BEGIN -->"
cut_body_after = "<!-- COMMIT-NOTES-END-->"

[update]
require_automerge_label = false

# Auto update label is sharedwith Luna
autoupdate_label = "luna/autoupdate"

# Ignore bots or other apps with automerge built in and kodiak should ignore then
ignored_usernames = ["valarie-ci-bot", "dependabot-preview", "luna-bot"]

# diana:{diana_urn_flavor}:{remote}:{source}:{version}:{remote_path}:{type}
# diana:2:github:tprasadtp/templates::bots/kodiak.toml:static
