name: build
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  # Build docker images
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: |
          make show-vars-base
          make docker-lint

      - name: Make Variables for Debugging
        run: |
          make show-vars-base || true
          make show-vars-docker || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@79d4afbba1b4eff8b9a98e3d2e58c4dbaf094e2b
        with:
          version: latest
          install-only: true

      - name: Build snapshot
        run: make snapshot

      - name: Smoke test
        run: |
          echo "Modify docker compose to run current build"
          sed -i "s/ghcr.io\/tprasadtp\/apt-cacher-ng:latest/ghcr.io\/tprasadtp\/apt-cacher-ng:${GITHUB_SHA}-dev-amd64/g" docker-compose.yml
          docker-compose -p apt-cacher-ng -f docker-compose.yml up -d
          echo "Test if Proxy works"
          docker run --rm --network=apt-cacher-ng_cache \
            ubuntu:focal bash -c \
            'printf "Acquire::HTTP::Proxy \"http://10.222.222.222\";\nAcquire::HTTPS::Proxy \"false\";" > /etc/apt/apt.conf.d/01-buildtime-proxy && apt-get update'
          echo "Teardown"
          docker-compose -p apt-cacher-ng -f docker-compose.yml down

      - uses: actions/cache@v2
        with:
          path: .trivy
          key: ${{ runner.os }}-trivy-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@a7a829a4345428ddd92ca57b18257440f6a18c90
        with:
          scan-type: 'image'
          vuln-type: os
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          image-ref: 'ghcr.io/tprasadtp/apt-cacher-ng:${{ github.sha }}-amd64'
          cache-dir: .trivy

      - name: Correct Trivy cache permissions
        run: sudo chown -R $USER:$GROUP .trivy
        if: always()
